package com.example.llmchat.invariants;

public enum InvariantGuardType {
    NONE,
    VALIDATION_BEFORE_EXECUTION_COMPLETE,
    EXECUTION_WITHOUT_CONSENT,
    MATERIAL_DURING_CLARIFICATION,
    MATERIAL_DURING_AGREEMENT,
    ACADEMIC_INTEGRITY,
    PHASE_ROLLBACK_REQUEST,
    SKIP_TOPIC_IN_EXECUTION,
    LECTURE_DURING_VALIDATION,
    STRUCTURED_PREP_WITHOUT_PLANNING,
    PROFILE_CONSTRAINT_VIOLATION,
    REFUSAL_FORMAT
}
